# 开发环境配置

spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cn-ben?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chennan
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  # ActiveMQ连接配置
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

# Dubbo配置
dubbo:
  application:
    name: ben-service
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.cn.ben.service.impl

# 延时队列配置
delay:
  queue:
    interval:
    - 0
    - 1
    - 4
    - 10
    - 30
    - 60
    - 120
    - 360
    - 900